### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by c0nnector** [boxme/SquareCamera#1]
Hey thanks for sharing! 

Just tried it and i have a few observations. 

The photo taken inside the square, is not the same as the photo saved. I think the bottom of the saved photo needs a bit of cropping.

If the phone goes into landscape mode the result picture looks kinda streched.

Front camera, try flipping the image. By default the image produced looks weird, you need to invert it

**Comment by boxme** [comment]
Thanks for your feedbacks. 

The cropping issue is now solved in the latest commit.

I have set the library to only in Portrait. I know this is not the best solution, but due to the time constraint I have, following the behaviour of most other camera apps seems to be the next logical step for me to take.

Same goes to using the front camera, the camera apps that I have (nexus 5 & s2) are showing the same inverted image. Hence, I keep it that way to stay in line with what the user might expect.
